M48
; DRILL file {KiCad (6.0.10)} date Mon Mar  6 12:11:44 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-03-06T12:11:44-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.10)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
%
G90
G05
T1
X1.99Y-3.08
X2.0Y-5.16
X4.81Y-5.14
X4.88Y-3.09
T0
M30
